#!/usr/bin/env bash
# DNS优化模块
# Module: dns
# Description: DNS Optimization
# Description(zh): DNS优化

# 定义可用的DNS服务器（名称 -> IP列表）
declare -A DNS_SERVERS=(
    ["114"]="114.114.114.114 114.114.115.115"
    ["阿里"]="223.5.5.5 223.6.6.6"
    ["腾讯"]="119.29.29.29 182.254.116.116"
    ["Cloudflare"]="1.1.1.1 1.0.0.1"
)

run_dns() {
    log_info "===== DNS优化模块 ====="

    # 检测当前DNS配置
    detect_current_dns

    # 选择DNS服务商
    echo "可用的DNS服务商："
    local i=1
    local names=()
    for name in "${!DNS_SERVERS[@]}"; do
        echo "  $i. $name (${DNS_SERVERS[$name]})"
        names+=("$name")
        ((i++))
    done
    echo "  $i. 自定义"
    echo "  0. 返回上级菜单"

    read -rp "请选择DNS服务商 [0-$i]: " choice
    if [[ "$choice" == "0" ]]; then
        return
    fi

    local selected_name
    local selected_servers
    if [[ "$choice" -le ${#names[@]} ]]; then
        selected_name="${names[$((choice-1))]}"
        selected_servers="${DNS_SERVERS[$selected_name]}"
    elif [[ "$choice" -eq $i ]]; then
        read -rp "请输入自定义DNS服务器（多个用空格分隔）: " selected_servers
        selected_name="custom"
    else
        log_error "无效选择"
        return
    fi

    if [[ -z "$selected_servers" ]]; then
        log_error "未指定DNS服务器"
        return
    fi

    # 确认修改
    if ! confirm "将DNS修改为 $selected_name ($selected_servers)，是否继续？"; then
        log_info "用户取消DNS修改"
        return
    fi

    # 根据系统环境应用DNS
    apply_dns "$selected_servers"
}

detect_current_dns() {
    log_info "检测当前DNS配置..."
    if [[ "$OS_NAME" == "macos" ]]; then
        # macOS
        scutil --dns | grep 'nameserver' | head -3
    elif [[ "$HAS_SYSTEMD" == "true" ]] && systemctl is-active systemd-resolved >/dev/null 2>&1; then
        # systemd-resolved
        systemd-resolve --status | grep "DNS Servers" -A2
    else
        # 传统 /etc/resolv.conf
        cat /etc/resolv.conf | grep nameserver
    fi
}

apply_dns() {
    local servers="$1"
    if [[ "$ENV_TYPE" == WSL* ]]; then
        apply_dns_wsl "$servers"
    elif [[ "$OS_NAME" == "macos" ]]; then
        apply_dns_macos "$servers"
    elif [[ "$HAS_SYSTEMD" == "true" ]] && systemctl is-active systemd-resolved >/dev/null 2>&1; then
        apply_dns_systemd_resolved "$servers"
    else
        apply_dns_resolv_conf "$servers"
    fi
}

apply_dns_resolv_conf() {
    local servers="$1"
    local resolv_conf="/etc/resolv.conf"

    check_root

    # 生成新的 resolv.conf 内容
    local content="# Generated by devboost on $(date)\n"
    for s in $servers; do
        content+="nameserver $s\n"
    done
    # 保留原有 search 行？简单起见只保留nameserver
    # 如果需要保留，可以解析原文件中的 search 行并附加

    safe_write "$resolv_conf" "$(echo -e "$content")" "dns"
    log_info "DNS已更新为：$servers"
}

apply_dns_systemd_resolved() {
    local servers="$1"
    # 对于 systemd-resolved，通常通过 /etc/systemd/resolved.conf 配置
    local conf_file="/etc/systemd/resolved.conf"
    check_root

    # 备份原文件
    backup_file "$conf_file" "dns"

    # 修改或添加 DNS 行
    if grep -q "^DNS=" "$conf_file"; then
        sed -i "s/^DNS=.*/DNS=$servers/" "$conf_file"
    else
        echo "DNS=$servers" >> "$conf_file"
    fi

    # 重启服务
    systemctl restart systemd-resolved
    log_info "已通过 systemd-resolved 应用 DNS：$servers"
}

apply_dns_macos() {
    local servers="$1"
    log_info "macOS DNS 配置需要手动设置或通过 networksetup 命令"
    # 简单提示
    echo "请在系统偏好设置中修改DNS，或使用命令："
    echo "sudo networksetup -setdnsservers Wi-Fi $servers"
    # 也可以尝试自动获取当前网络服务
}

apply_dns_wsl() {
    local servers="$1"
    log_warn "WSL 中 /etc/resolv.conf 可能被 Windows 自动覆盖"
    log_warn "建议在 Windows 中修改 DNS 或设置 WSL 生成 resolv.conf 的选项"
    # 尝试修改 /etc/resolv.conf 但加上 immutable 属性
    local resolv_conf="/etc/resolv.conf"
    check_root

    # 移除不可变属性（如果存在）
    chattr -i "$resolv_conf" 2>/dev/null || true

    apply_dns_resolv_conf "$servers"

    # 设置不可变防止覆盖
    chattr +i "$resolv_conf" 2>/dev/null && log_info "已设置 $resolv_conf 为不可变，防止被覆盖"
}